name: Publish Container

on:
  push:
    branches:
      - main

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and Push to GitHub Container Registry
        run: |
          docker build . --tag ghcr.io/eos-uiux-solutions/strapi:latest
          docker push ghcr.io/eos-uiux-solutions/strapi:latest

  publish-test-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and Push to GitHub Container Registry
        run: |
          docker build -f 'Dockerfile.test' . --tag ghcr.io/eos-uiux-solutions/strapi-test:latest
          docker push ghcr.io/eos-uiux-solutions/strapi-test:latest
