name: Publish Container

on:
  push:
    branches:
      - tests/bootstrap

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Push to GitHub Container Registry
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ghcr.io/eos-uiux-solutions/strapi
          registry: ghcr.io
          githubOrg: EOS-uiux-Solutions
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

  publish-test-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Push the Test Image to GitHub Container Registry
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ghcr.io/eos-uiux-solutions/strapi
          registry: ghcr.io
          dockerfile: Dockerfile.test
          githubOrg: SundeepChand
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.PAT }}